Repository openscd/open-scd, pull requests merged in 2021-03, with the labels that each got.

#137 fix(logging): do not log results of long running processes twice
  src/Importing.ts
  src/Validating.ts
  src/Waiting.ts
  src/foundation.ts
  src/open-scd.ts
  test/integration/open-scd.test.ts
  test/unit/Waiting.test.ts
  test/unit/foundation.test.ts
Labels: Kind: Bug, Priority: High, Reviewed: Confirmed

#124 feat: add extension manager
  __snapshots__/open-scd.md
  index.html
  package-lock.json
  package.json
  public/json/de.json
  public/json/en.json
  public/json/plugins.json
  src/Editing.ts
  src/Logging.ts
  src/Plugging.ts
  src/Setting.ts
  src/Waiting.ts
  src/carehtml/transform.js
  src/carehtml/wrap.ts
  src/editors/Communication.ts
  src/editors/Substation.ts
  src/editors/communication/connectedap-editor.ts
  src/editors/substation/guess-wizard.ts
  src/editors/substation/lnodewizard.ts
  src/editors/substation/substation-editor.ts
  src/editors/templates/enum-type-editor.ts
  src/editors/templates/enum-val-editor.ts
  src/open-scd.ts
  src/plugin.ts
  src/themes.ts
  src/triggered/SubscriberInfo.ts
  src/wizard-dialog.ts
  src/wizard-textfield.ts
  test/data.ts
  test/integration/editors/templates/enum-val-editor-wizarding.test.ts
  test/integration/open-scd.test.ts
  test/unit/Plugging.test.ts
  test/unit/editors/subscriberinfo.test.ts
  test/unit/mock-plugger.ts
  test/unit/plugin.test.ts
Labels: Kind: Feature, Priority: Critical, Reviewed: Confirmed

#138 fix(editors/styling): add abbrevaition style
  src/editors/communication/foundation.ts
  src/editors/substation/foundation.ts
Labels: Kind: Bug, Priority: High, Reviewed: Confirmed

#136 feat(logging): add buttons to filter log messages by kind
  __snapshots__/open-scd.md
  package-lock.json
  package.json
  src/Logging.ts
  src/foundation.ts
  src/icons.ts
  src/open-scd.ts
  test/unit/Logging.test.ts
  tsconfig.json
Labels: Kind: Enhancement, Priority: Medium, Reviewed: Confirmed

#140 fix(editors/substation/conducting-equipment): overlapping icon buttons
  __snapshots__/conducting-equipment-editor.md
  __snapshots__/connectedap-editor.md
  src/editors/communication/connectedap-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  test/integration/editors/communication/connectedap-editor-wizarding-editing.test.ts
  test/integration/editors/communication/connectedap-editor-wizarding.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding.test.ts
Labels: Kind: Bug, Priority: Medium, Reviewed: Confirmed

#155 test(editors): add missing integration tests
  test/data.ts
  test/integration/editors/communication/Communication.test.ts
  test/integration/editors/substation/Substation.test.ts
  test/integration/editors/templates/Templates.test.ts
  test/unit/editors/communication/ConnectedAPEditor.test.ts
  test/unit/editors/communication/SubNetwork.test.ts
  test/unit/editors/communication/conductingap-editor.test.ts
  test/unit/editors/communication/subnetwork-editor.test.ts
Labels: Kind: Maintenance

#161 fix(editors/substation): remove horizontal scroll bar on overflow
  src/editors/substation/substation-editor.ts
Labels: Kind: Bug

#160 fix: allow re-opening the same file again
  src/open-scd.ts
Labels: Kind: Bug

#163 chore: extern carehtml dependency
  package-lock.json
  package.json
  src/Plugging.ts
  src/carehtml/transform.js
  src/carehtml/wrap.ts
Labels: Kind: Maintenance, Reviewed: Prioritized
