Repository openscd/open-scd, pull requests merged in 2021-11, with the labels that each got.

#338 Add finder list
  __snapshots__/create wizard for FCDA element.md
  __snapshots__/dataset wizards.md
  __snapshots__/filtered-list.md
  __snapshots__/finder-list.md
  __snapshots__/finder-pane.md
  package-lock.json
  src/filtered-list.ts
  src/finder-list.ts
  src/finder-pane.ts
  src/foundation.ts
  src/menu/Help.ts
  src/open-scd.ts
  src/wizards/dataset.ts
  src/wizards/fcda.ts
  src/wizards/foundation/functions.ts
  src/wizards/wizard-library.ts
  test/integration/wizards/fcda-wizarding-editing-integration.test.ts
  test/testfiles/wizards/fcda.scd
  test/unit/finder-list.test.ts
  test/unit/finder-pane.test.ts
  test/unit/foundation.test.ts
  test/unit/wizards/dataset.test.ts
  test/unit/wizards/fcda.test.ts
  test/unit/wizards/foundation/functions.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized, Priority: Urgent

#374 feat(menu/UpdateDescritionABB): update ExtRef with internal signal description
  __snapshots__/Update method for desc attributes in ABB IEDs.md
  __snapshots__/open-scd.md
  public/js/plugins.js
  src/foundation.ts
  src/menu/UpdateDescriptionABB.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/menu/UpdateDescritionABB.test.ts
  test/testfiles/updatedesc/updatedescABB.scd
  test/unit/menu/UpdateDescritionABB.test.ts
Labels: Kind: Enhancement

#400 refactor(editor-container): replace with more generic action-pane
  __snapshots__/action-pane.md
  __snapshots__/bay-editor.md
  __snapshots__/substation-editor.md
  __snapshots__/voltage-level-editor.md
  src/action-pane.ts
  src/editor-container.ts
  src/zeroline-pane.ts
  src/zeroline/bay-editor.ts
  src/zeroline/foundation.ts
  src/zeroline/substation-editor.ts
  src/zeroline/voltage-level-editor.ts
  test/integration/zeroline/bay-editor-wizarding-editing.test.ts
  test/integration/zeroline/substation-editor-wizarding-editing.test.ts
  test/integration/zeroline/voltage-level-editor-wizarding-editing.test.ts
  test/unit/action-pane.test.ts
Labels: Kind: Maintenance, Reviewed: Prioritized, Priority: Urgent
