Repository openscd/open-scd, pull requests merged in 2021-02, with the labels that each got.

#122 fix(themes): add list-item text colors
  src/Logging.ts
  src/themes.ts
Labels: bug, usability

#111 Create network configuration plug in
  __snapshots__/Communication Plugin.md
  __snapshots__/connectedap-editor.md
  __snapshots__/subnetwork-editor.md
  src/editors/Communication.ts
  src/editors/communication/connectedap-editor.ts
  src/editors/communication/foundation.ts
  src/editors/communication/p-types.ts
  src/editors/communication/subnetwork-editor.ts
  src/editors/substation/foundation.ts
  src/editors/substation/lnodewizard.ts
  src/foundation.ts
  src/open-scd.ts
  src/translations/de.ts
  src/translations/en.ts
  test/data.ts
  test/foundation.ts
  test/integration/editors/communication/Communication.test.ts
  test/integration/editors/communication/connectedap-editor-wizarding-editing.test.ts
  test/integration/editors/communication/connectedap-editor-wizarding.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding-editing.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding.test.ts
  test/integration/editors/substation/Substation.test.ts
  test/integration/editors/substation/bay-editor-wizarding-editing.test.ts
  test/integration/editors/substation/bay-editor-wizarding.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding.test.ts
  test/integration/editors/substation/guess-wizarding-editing.test.ts
  test/integration/editors/substation/lnodewizard.test.ts
  test/integration/editors/substation/substation-editor-wizarding-editing.test.ts
  test/integration/editors/substation/substation-editor-wizarding.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding-editing.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding.test.ts
  test/integration/open-scd.test.ts
  test/unit/editors/ConnectedAPEditor.test.ts
  test/unit/editors/SubNetwork.test.ts
  test/unit/editors/conductingap-editor.test.ts
  test/unit/editors/subnetwork-editor.test.ts
Labels: enhancement

#125 docs(changelog): add standard-version to dev dependencies to auto gen…
  package-lock.json
  package.json
Labels: Kind: Maintenance, Priority: Medium

#131 fix(lnodewizard): client lns saved with empty string instead of Clien…
  src/editors/substation/lnodewizard.ts
Labels: Kind: Bug, Priority: Critical

#126 feat(scl-transformation): automatic IEDName subscriber auto-complete
  __snapshots__/open-scd.md
  src/Importing.ts
  src/open-scd.ts
  src/transform/SubscriberInfo.ts
  src/translations/de.ts
  src/translations/en.ts
  test/data.ts
  test/integration/open-scd.test.ts
  test/unit/editors/subscriberinfo.test.ts
Labels: Kind: Enhancement, Priority: Critical, Reviewed: Confirmed

#110 Add enum type editor
  __snapshots__/Communication Plugin.md
  __snapshots__/Substation Plugin.md
  __snapshots__/Templates Plugin.md
  __snapshots__/enum-type-editor.md
  __snapshots__/enum-val-editor.md
  __snapshots__/open-scd.md
  index.html
  karma.conf.cjs
  package.json
  public/xml/templates.scd
  src/Editing.ts
  src/Setting.ts
  src/Validating.ts
  src/Wizarding.ts
  src/editors/Templates.ts
  src/editors/communication/connectedap-editor.ts
  src/editors/communication/subnetwork-editor.ts
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/foundation.ts
  src/editors/substation/guess-wizard.ts
  src/editors/substation/lnodewizard.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/editors/templates/enum-type-editor.ts
  src/editors/templates/enum-val-editor.ts
  src/editors/templates/foundation.ts
  src/foundation.ts
  src/open-scd.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizard-dialog.ts
  test/data.ts
  test/foundation.ts
  test/integration/editors/communication/connectedap-editor-wizarding-editing.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding-editing.test.ts
  test/integration/editors/substation/bay-editor-wizarding-editing.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/substation-editor-wizarding-editing.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding-editing.test.ts
  test/integration/editors/templates/Templates.test.ts
  test/integration/editors/templates/enum-type-editor-wizarding-editing.test.ts
  test/integration/editors/templates/enum-type-editor-wizarding.test.ts
  test/integration/editors/templates/enum-val-editor-wizarding-editing.test.ts
  test/integration/editors/templates/enum-val-editor-wizarding.test.ts
  test/integration/open-scd.test.ts
  test/unit/editors/SubNetwork.test.ts
  test/unit/editors/substation/BayEditor.test.ts
  test/unit/editors/substation/ConductingEquipmentEditor.test.ts
  test/unit/editors/substation/SubstationEditor.test.ts
  test/unit/editors/substation/VoltageLevelEditor.test.ts
  test/unit/editors/substation/bay-editor.test.ts
  test/unit/editors/substation/conducting-equipment-editor.test.ts
  test/unit/editors/substation/lnodewizard.test.ts
  test/unit/editors/substation/substation-editor.test.ts
  test/unit/editors/substation/voltage-level-editor.test.ts
  test/unit/editors/templates/EnumTypeEditor.test.ts
  test/unit/editors/templates/EnumValEditor.test.ts
  test/unit/editors/templates/enum-type-editor.test.ts
  test/unit/editors/templates/enum-val-editor.test.ts
Labels: Kind: Feature, Priority: Critical, Reviewed: Confirmed
