Repository openscd/open-scd, pull requests merged in 2021-12, with the labels that each got.

#436 refactor: add action-icon
  src/action-icon.ts
  src/editors/communication/connectedap-editor.ts
  src/zeroline/conducting-equipment-editor.ts
  src/zeroline/ied-editor.ts
  test/unit/__snapshots__/action-icon.test.snap.js
  test/unit/action-icon.test.ts
  test/unit/editors/communication/__snapshots__/conductingap-editor.test.snap.js
  test/unit/editors/communication/conductingap-editor.test.ts
  test/unit/zeroline/ConductingEquipmentEditor.test.ts
  test/unit/zeroline/__snapshots__/conducting-equipment-editor.test.snap.js
  test/unit/zeroline/__snapshots__/ied-editor.test.snap.js
  test/unit/zeroline/conducting-equipment-editor.test.ts
  test/unit/zeroline/ied-editor.test.ts
Labels: Kind: Maintenance, Reviewed: Prioritized

#446 fix(wizards/fcda): remove incorrect iedName from FCDA
  src/wizards/fcda.ts
  test/integration/wizards/fcda-wizarding-editing-integration.test.ts
  test/unit/wizards/fcda.test.ts
Labels: Kind: Bug, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#438 feat(zeroline/ied-editor): add show report action
  src/zeroline/ied-editor.ts
  test/integration/zeroline/ied-editor-wizarding-integration.test.ts
  test/unit/zeroline/__snapshots__/ied-editor.test.snap.js
  test/unit/zeroline/ied-editor.test.ts
Labels: Kind: Enhancement
