Repository openscd/open-scd, pull requests merged in 2021-04, with the labels that each got.

#168 feat(updatesubstation): add special merge functionality for substation section
  __snapshots__/open-scd.md
  public/json/plugins.json
  src/foundation.ts
  src/triggered/UpdateSubstation.ts
  src/wizard-dialog.ts
  src/wizards.ts
  test/data.ts
  test/unit/foundation.test.ts
Labels: Kind: Enhancement, Kind: Feature, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#164 feat(merge-plugin): add general functionality to merge two SCL files
  __snapshots__/open-scd.md
  public/json/plugins.json
  src/foundation.ts
  src/open-scd.ts
  src/translations/de.ts
  src/translations/en.ts
  src/triggered/Merge.ts
  src/triggered/UpdateSubstation.ts
  src/wizard-dialog.ts
  src/wizards.ts
  test/data.ts
  test/integration/editors/communication/subnetwork-editor-wizarding-editing.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding.test.ts
  test/integration/open-scd.test.ts
  test/testfiles/updatesubstation-ours.scd
  test/unit/editors/updatesubstation.test.ts
  test/unit/foundation.test.ts
Labels: Kind: Enhancement, Kind: Feature, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#169 feat(communicationmapping): add commMappingWizard and cbConnectionWizard
  __snapshots__/filtered-list.md
  __snapshots__/open-scd.md
  public/json/plugins.json
  public/xml/testfiles/comm-map.scd
  src/editors/communication/connectedap-editor.ts
  src/editors/communication/subnetwork-editor.ts
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/foundation.ts
  src/editors/substation/guess-wizard.ts
  src/editors/substation/lnodewizard.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/editors/templates/enum-type-editor.ts
  src/editors/templates/enum-val-editor.ts
  src/editors/templates/foundation.ts
  src/filtered-list.ts
  src/foundation.ts
  src/icons.ts
  src/open-scd.ts
  src/translations/de.ts
  src/translations/en.ts
  src/triggered/CommunicationMapping.ts
  src/wizard-dialog.ts
  src/wizards.ts
  test/data.ts
  test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
  test/mock-wizard-editor.ts
  test/unit/editors/communicationmapping.test.ts
  test/unit/filtered-list.test.ts
  test/unit/foundation.test.ts
Labels: Kind: Feature, Priority: Important, Priority: Urgent

#170 feat(communicationmapping): create control block connections with clientln
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  src/triggered/CommunicationMapping.ts
  test/integration/editors/triggered/CommunicationMappingPlugin.test.ts
  test/testfiles/comm-map.scd
  test/unit/editors/communicationmapping.test.ts
  test/unit/foundation.test.ts
Labels: Kind: Feature, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#173 fix(communicationmapping): ClientLN handling for LNs reside in AccessPoint
  src/triggered/CommunicationMapping.ts
Labels: Kind: Bug, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#180 Implement getreference function
  src/foundation.ts
  test/unit/foundation.test.ts
Labels: Kind: Enhancement, Priority: Important, Reviewed: Prioritized

#186 feat(logging): show snackbars on info and warning
  __snapshots__/open-scd.md
  src/Logging.ts
  test/integration/open-scd.test.ts
  test/unit/Logging.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized

#187 feat(filtered-list): add check all to filtered-list
  __snapshots__/filtered-list.md
  src/filtered-list.ts
  test/unit/filtered-list.test.ts
Labels: Kind: Enhancement, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#179 refactor(lnodewizard): remove LDevice page from lnodewizard
  src/editors/substation/lnodewizard.ts
  src/filtered-list.ts
  src/foundation.ts
  src/wizard-dialog.ts
  test/integration/editors/substation/bay-editor-wizarding-editing.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/lnodewizard.test.ts
  test/integration/editors/substation/substation-editor-wizarding-editing.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding-editing.test.ts
  test/testfiles/lnodewizard.scd
  test/unit/editors/substation/lnodewizard.test.ts
  test/unit/filtered-list.test.ts
Labels: Priority: Important, Priority: Urgent, Reviewed: Prioritized

#181 Fix update missing substation
  src/foundation.ts
  src/triggered/UpdateSubstation.ts
  src/wizard-dialog.ts
  src/wizards.ts
Labels: Kind: Enhancement, Priority: Important, Reviewed: Prioritized

#188 fix(open-scd): fix createNewProject for Edition 2
  src/open-scd.ts
  test/integration/open-scd.test.ts
Labels: Kind: Bug, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#190 doc(roadmap): initial readme
  ROADMAP.md
Labels: Kind: Documentation

#189 feat(communication-editor): show all connected ap within ied
  __snapshots__/subnetwork-editor.md
  src/editors/Communication.ts
  src/editors/communication/connectedap-editor.ts
  src/editors/communication/foundation.ts
  src/editors/communication/subnetwork-editor.ts
  test/unit/editors/communication/ConnectedAPEditor.test.ts
  test/unit/editors/communication/SubNetwork.test.ts
Labels: Kind: Enhancement, Priority: Important, Priority: Urgent, Reviewed: Prioritized
