Repository openscd/open-scd, pull requests merged in 2021-01, with the labels that each got.

#104 Pretty print
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/guess-wizard.ts
  src/editors/substation/lnodewizard.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/foundation.ts
  src/open-scd.ts
Labels: bug

#109 Add clone feature
  src/editors/substation/foundation.ts
  test/integration/editors/bay-editor-wizarding-editing.test.ts
  test/integration/editors/voltage-level-editor-wizarding-editing.test.ts
Labels: bug, help wanted

#97 Add import ieds function
  __snapshots__/open-scd.md
  src/Importing.ts
  src/Logging.ts
  src/foundation.ts
  src/open-scd.ts
  src/translations/de.ts
  src/translations/en.ts
  test/data.ts
  test/integration/open-scd.test.ts
Labels: enhancement
