Repository openscd/open-scd, pull requests merged in 2021-07, with the labels that each got.

#238 Add about box
  __snapshots__/open-scd.md
  public/js/plugins.js
  src/icons.ts
  src/menu/Help.ts
  test/integration/menu/HelpPlugin.test.ts
  test/unit/Plugging.test.ts
  tsconfig.json
Labels: Kind: Enhancement, Priority: Urgent, Reviewed: Prioritized

#233 feat(wizard-dialog): add code editor to wizards
  __snapshots__/open-scd.md
  __snapshots__/wizard-dialog.md
  package-lock.json
  package.json
  public/ace/ext-searchbox.js
  public/ace/mode-xml.js
  public/ace/theme-solarized_dark.js
  public/ace/theme-solarized_light.js
  public/ace/worker-xml.js
  src/Setting.ts
  src/editors/communication/connectedap-editor.ts
  src/editors/communication/subnetwork-editor.ts
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/lnodewizard.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/editors/templates/datype-wizards.ts
  src/editors/templates/dotype-wizards.ts
  src/editors/templates/enumtype-wizard.ts
  src/editors/templates/lnodetype-wizard.ts
  src/foundation.ts
  src/menu/NewProject.ts
  src/open-scd.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizard-dialog.ts
  src/wizards.ts
  test/integration/validators/ValidateSchema.test.ts
  test/unit/wizard-dialog.test.ts
Labels: Kind: Enhancement, Kind: Feature, Priority: Important, Reviewed: Prioritized

#241 feat(templates/lnodetype-wizards): add helper wizard for missing lnClass in templates
  __snapshots__/LNodeType wizards.md
  src/editors/Templates.ts
  src/editors/templates/lnodetype-wizard.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/editors/templates/lnodetype-wizard.test.ts
Labels: Kind: Enhancement, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#245 fix(substation/lnodewizard): oldNodes are only child nodes of an element
  src/editors/substation/lnodewizard.ts
  src/foundation.ts
  test/integration/editors/substation/lnodewizard.test.ts
  test/unit/foundation.test.ts
Labels: Priority: Important, Priority: Urgent, Reviewed: Prioritized

#242 refactor(wizards): move wizards in substation editor to wizard library
  src/editors/Substation.ts
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/conducting-equipment-types.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/wizards/bay.ts
  src/wizards/conductingequipment.ts
  src/wizards/lnode.ts
  src/wizards/substation.ts
  src/wizards/voltagelevel.ts
  src/wizards/wizard-library.ts
  test/integration/editors/substation/lnodewizard.test.ts
  test/unit/editors/substation/BayEditor.test.ts
  test/unit/editors/substation/ConductingEquipmentEditor.test.ts
  test/unit/editors/substation/SubstationEditor.test.ts
  test/unit/editors/substation/VoltageLevelEditor.test.ts
  test/unit/editors/substation/lnodewizard.test.ts
Labels: Reviewed: Prioritized

#250 feat(wizard-select): add nullabl mwc-select web-component
  src/wizard-select.ts
  test/unit/wizard-select.test.ts
Labels: Reviewed: Prioritized

#247 refactor(logging): add reset kind log event
  __snapshots__/open-scd.md
  src/Logging.ts
  src/foundation.ts
  src/icons.ts
  src/menu/NewProject.ts
  src/menu/OpenProject.ts
  src/open-scd.ts
  test/unit/Logging.test.ts
Labels: Kind: Maintenance, Priority: Urgent, Reviewed: Prioritized

#248 refactor: add finder-pane for tree nagivation
  __snapshots__/finder-pane.md
  public/md/Connect-Report-Control-Blocks-with-ClientLN.md
  public/md/DataTypeTemplate-editor.md
  public/md/Guess-substation-structure.md
  public/md/Home.md
  public/md/How-to-install-OpenSCD-offline.md
  public/md/Importing-IEDs.md
  public/md/Manage-save-project.md
  public/md/Merge-functionality.md
  public/md/Update-GOOSE-subscriber-info-in-SCL.md
  public/md/_Sidebar.md
  src/finder-pane.ts
  src/foundation.ts
  src/open-scd.ts
  test/unit/finder-pane.test.ts
Labels: Good first issue, Kind: Enhancement, Priority: Important, Reviewed: Prioritized

#249 Add user manual
  __snapshots__/enum-type-editor.md
  __snapshots__/enum-val-editor.md
  __snapshots__/finder-pane.md
  package-lock.json
  package.json
  public/md/Communication.md
  public/md/DataTypeTemplates.md
  public/md/Home.md
  public/md/IED.md
  public/md/OpenSCD-Editor-Features.md
  public/md/SCL-Sections.md
  public/md/Substation.md
  public/md/_Sidebar.md
  src/finder-pane.ts
  src/menu/Help.ts
  test/integration/menu/HelpPlugin.test.ts
  test/integration/menu/NewProject.test.ts
Labels: Kind: Documentation, Priority: Important, Reviewed: Prioritized

#264 fix(plugging): fix plugin auto-update
  src/Plugging.ts
Labels: Kind: Bug, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#266 fix(logging): remove superfluous invisible reset filter
  __snapshots__/open-scd.md
  src/Logging.ts
Labels: Kind: Bug, Priority: Important, Reviewed: Prioritized

#251 feat(zeroline-pane): add combined Substation and IED overview
  __snapshots__/Substation Plugin.md
  __snapshots__/bay-editor wizarding integration.md
  __snapshots__/bay-editor.md
  __snapshots__/conducting-equipment-editor wizarding integration.md
  __snapshots__/conducting-equipment-editor.md
  __snapshots__/open-scd.md
  __snapshots__/substation-editor wizarding integration.md
  __snapshots__/substation-editor.md
  __snapshots__/voltage-level-editor wizarding integration.md
  __snapshots__/voltage-level-editor.md
  __snapshots__/zeroline-pane.md
  src/Setting.ts
  src/editors/Substation.ts
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-types.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/bay.ts
  src/wizards/conductingequipment.ts
  src/wizards/substation.ts
  src/zeroline-pane.ts
  src/zeroline/bay-editor.ts
  src/zeroline/conducting-equipment-editor.ts
  src/zeroline/foundation.ts
  src/zeroline/ied-editor.ts
  src/zeroline/substation-editor.ts
  src/zeroline/voltage-level-editor.ts
  test/integration/editors/Substation.test.ts
  test/integration/editors/substation/guess-wizarding-editing.test.ts
  test/integration/zeroline/bay-editor-wizarding-editing.test.ts
  test/integration/zeroline/bay-editor-wizarding.test.ts
  test/integration/zeroline/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/zeroline/conducting-equipment-editor-wizarding.test.ts
  test/integration/zeroline/substation-editor-wizarding-editing.test.ts
  test/integration/zeroline/substation-editor-wizarding.test.ts
  test/integration/zeroline/voltage-level-editor-wizarding-editing.test.ts
  test/integration/zeroline/voltage-level-editor-wizarding.test.ts
  test/testfiles/zeroline/iedalloctest.scd
  test/testfiles/zeroline/substationonly.scd
  test/unit/zeroline-pane.test.ts
  test/unit/zeroline/BayEditor.test.ts
  test/unit/zeroline/ConductingEquipmentEditor.test.ts
  test/unit/zeroline/SubstationEditor.test.ts
  test/unit/zeroline/VoltageLevelEditor.test.ts
  test/unit/zeroline/bay-editor.test.ts
  test/unit/zeroline/conducting-equipment-editor.test.ts
  test/unit/zeroline/substation-editor.test.ts
  test/unit/zeroline/voltage-level-editor.test.ts
Labels: Reviewed: Prioritized

#269 fix(validatetemplates): don't require "Oper" if ctlModel=status-only
  src/translations/de.ts
  src/translations/en.ts
  src/validators/ValidateSchema.ts
  src/validators/ValidateTemplates.ts
  test/integration/editors/templates/lnodetype-wizard.test.ts
  test/integration/validators/ValidateTemplates.test.ts
  test/testfiles/validators/datatypetemplateerrors.scd
  test/unit/validators/ValidateTemplates.test.ts
Labels: Kind: Bug, Priority: Important, Reviewed: Prioritized
