Repository openscd/open-scd, pull requests merged in 2021-06, with the labels that each got.

#201 feat(templates): add DAType basic manipulation capability
  LICENSE
  LICENSE.md
  __snapshots__/DAType wizards.md
  __snapshots__/Templates Plugin.md
  __snapshots__/filtered-list.md
  __snapshots__/subnetwork-editor.md
  package-lock.json
  package.json
  public/xml/templates.scd
  src/Wizarding.ts
  src/editors/Templates.ts
  src/editors/communication/subnetwork-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/editors/templates/datype-wizards.ts
  src/editors/templates/enum-type-editor.ts
  src/editors/templates/enum-val-editor.ts
  src/editors/templates/foundation.ts
  src/filtered-list.ts
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  test/foundation.ts
  test/integration/editors/templates/Templates.test.ts
  test/integration/editors/templates/datype-wizarding.test.ts
  test/testfiles/datypes.scd
Labels: Kind: Feature

#208 feat(editors/templates): add read-only DOType section
  __snapshots__/Templates Plugin.md
  src/editors/Templates.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/editors/templates/Templates.test.ts
  test/integration/editors/templates/datype-wizarding.test.ts
  test/testfiles/templates/datypes.scd
  test/testfiles/templates/missingdatatypes.scd
Labels: Kind: Feature

#206 refactor(triggered): make "Open project" a plugin
  __snapshots__/open-scd.md
  public/js/plugins.js
  src/Editing.ts
  src/Logging.ts
  src/Plugging.ts
  src/Validating.ts
  src/foundation.ts
  src/loaders/OpenProject.ts
  src/open-scd.ts
  test/integration/open-scd.test.ts
Labels: Kind: Maintenance, Priority: Important, Reviewed: Prioritized

#212 feat(editors/templates): add read-only LNodeType to
  __snapshots__/Templates Plugin.md
  src/editors/Templates.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/editors/templates/datype-wizarding.test.ts
  test/integration/editors/templates/dotype-wizarding.test.ts
Labels: Kind: Enhancement, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#213 feat(editors/templates/lnodetype-wizards): add basic lnodetype manipulation capabilities
  __snapshots__/DAType wizards.md
  __snapshots__/DOType wizards.md
  __snapshots__/LNodeType wizards.md
  __snapshots__/Templates Plugin.md
  public/xml/templates.scd
  src/editors/Templates.ts
  src/editors/templates/datype-wizards.ts
  src/editors/templates/dotype-wizards.ts
  src/editors/templates/foundation.ts
  src/editors/templates/lnodetype-wizard.ts
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/editors/templates/lnodetype-wizard.test.ts
  test/integration/open-scd.test.ts
Labels: Kind: Enhancement, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#221 refactor(editors/template): move EnumType from web-components to wizards
  __snapshots__/EnumType wizards.md
  __snapshots__/Templates Plugin.md
  __snapshots__/enum-type-editor.md
  __snapshots__/enum-val-editor.md
  src/editors/Templates.ts
  src/editors/templates/datype-wizards.ts
  src/editors/templates/dotype-wizards.ts
  src/editors/templates/enum-type-editor.ts
  src/editors/templates/enum-val-editor.ts
  src/editors/templates/enumtype-wizard.ts
  src/editors/templates/foundation.ts
  src/editors/templates/lnodetype-wizard.ts
  test/integration/editors/templates/datype-wizarding.test.ts
  test/integration/editors/templates/dotype-wizarding.test.ts
  test/integration/editors/templates/enum-type-editor-wizarding-editing.test.ts
  test/integration/editors/templates/enum-type-editor-wizarding.test.ts
  test/integration/editors/templates/enum-val-editor-wizarding-editing.test.ts
  test/integration/editors/templates/enum-val-editor-wizarding.test.ts
  test/integration/editors/templates/enumtype-wizarding.test.ts
  test/integration/editors/templates/lnodetype-wizard.test.ts
  test/unit/editors/templates/EnumTypeEditor.test.ts
  test/unit/editors/templates/EnumValEditor.test.ts
  test/unit/editors/templates/enum-type-editor.test.ts
  test/unit/editors/templates/enum-val-editor.test.ts
Labels: Kind: Enhancement, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#226 test: move test information to test.scd files
  __snapshots__/bay-editor wizarding integration.md
  __snapshots__/conducting-equipment-editor wizarding integration.md
  __snapshots__/conductingap-editor wizarding integration.md
  __snapshots__/subnetwork-editor wizarding integration.md
  __snapshots__/substation-editor wizarding integration.md
  __snapshots__/voltage-level-editor wizarding integration.md
  test/data.ts
  test/integration/editors/communication/Communication.test.ts
  test/integration/editors/communication/connectedap-editor-wizarding-editing.test.ts
  test/integration/editors/communication/connectedap-editor-wizarding.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding-editing.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding.test.ts
  test/integration/editors/substation/Substation.test.ts
  test/integration/editors/substation/bay-editor-wizarding-editing.test.ts
  test/integration/editors/substation/bay-editor-wizarding.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding.test.ts
  test/integration/editors/substation/guess-wizarding-editing.test.ts
  test/integration/editors/substation/substation-editor-wizarding-editing.test.ts
  test/integration/editors/substation/substation-editor-wizarding.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding-editing.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding.test.ts
  test/integration/editors/triggered/ImportIedsPlugin.test.ts
  test/integration/open-scd.test.ts
  test/testfiles/invalid2007B.scd
  test/testfiles/missingCommunication.scd
  test/testfiles/missingSubstation.scd
  test/testfiles/valid2003.scd
  test/testfiles/valid2007B.scd
  test/testfiles/valid2007B4.scd
  test/unit/Plugging.test.ts
  test/unit/Validating.test.ts
  test/unit/editors/communication/conductingap-editor.test.ts
  test/unit/editors/communication/subnetwork-editor.test.ts
  test/unit/editors/substation/bay-editor.test.ts
  test/unit/editors/substation/conducting-equipment-editor.test.ts
  test/unit/editors/substation/substation-editor.test.ts
  test/unit/editors/substation/voltage-level-editor.test.ts
  test/unit/foundation.test.ts
Labels: Kind: Maintenance

#227 refactor: pluginify validator, save and new project
  __snapshots__/open-scd.md
  public/js/plugins.js
  src/Editing.ts
  src/Hosting.ts
  src/Plugging.ts
  src/Validating.ts
  src/foundation.ts
  src/loaders/NewProject.ts
  src/open-scd.ts
  src/savers/SaveProject.ts
  src/schemas.ts
  src/translations/en.ts
  src/validators/ValidateSchema.ts
  test/integration/loaders/NewProject.test.ts
  test/integration/open-scd.test.ts
  test/integration/validators/ValidateSchema.test.ts
  test/unit/Validating.test.ts
  test/unit/mock-validator.ts
Labels: Kind: Maintenance, Priority: Urgent, Reviewed: Prioritized

#231 fix(wizard-dialog): remove button actions only after action was successful
  src/wizard-dialog.ts
  test/unit/wizard-dialog.test.ts
Labels: Kind: Bug, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#236 fix(templates): adjust width setting to better fit to small portable devices
  src/editors/Templates.ts
Labels: Kind: Bug, Priority: Important, Priority: Urgent, Reviewed: Prioritized

#229 feat(validators/validatetemplates): add validation based on NSD files
  README.md
  __snapshots__/enum-type-editor.md
  __snapshots__/enum-val-editor.md
  __snapshots__/open-scd.md
  public/js/plugins.js
  public/xml/IEC_61850-7-2_2007B3.nsd
  public/xml/IEC_61850-7-3_2007B3.nsd
  public/xml/IEC_61850-7-4_2007B3.nsd
  public/xml/IEC_61850-8-1_2003A2.nsd
  src/validators/ValidateTemplates.ts
  test/integration/validators/ValidateTemplates.test.ts
  test/testfiles/validators/datatypetemplateerrors.scd
  test/unit/validators/ValidateTemplates.test.ts
Labels: Kind: Feature, Priority: Important
