Repository openscd/open-scd, pull requests merged in 2022-05, with the labels that each got.

#712 bug(wizards): Update attributes of Terminal when updating Voltage Level/Bay name.
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/bay.ts
  src/wizards/conductingequipment.ts
  src/wizards/foundation/actions.ts
  src/wizards/foundation/references.ts
  src/wizards/powertransformer.ts
  src/wizards/voltagelevel.ts
  test/testfiles/wizards/references.scd
  test/unit/editors/singlelinediagram/wizards/bay.test.ts
  test/unit/editors/singlelinediagram/wizards/conductingequipment.test.ts
  test/unit/editors/singlelinediagram/wizards/powertransformer.test.ts
  test/unit/editors/substation/BayEditor.test.ts
  test/unit/wizards/bay.test.ts
  test/unit/wizards/dai.test.ts
  test/unit/wizards/foundation/references.test.ts
  test/unit/wizards/ied.test.ts
  test/unit/wizards/powertransformer.test.ts
  test/unit/wizards/substation.test.ts
  test/unit/wizards/test-support.ts
  test/unit/wizards/voltagelevel.test.ts
Labels: Kind: Bug

#732 feat(editor/ied): Add wizard/action to remove IED including references
  src/editors/IED.ts
  src/editors/ied/ied-container.ts
  src/editors/sampledvalues/subscriber-ied-list-smv.ts
  src/editors/subscription/subscriber-list.ts
  src/editors/substation/ied-editor.ts
  src/foundation.ts
  src/foundation/ied.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/foundation/references.ts
  src/wizards/ied.ts
  test/integration/editors/substation/ied-editor-wizarding-integration.test.ts
  test/unit/editors/ied/__snapshots__/ied-container.test.snap.js
  test/unit/editors/substation/__snapshots__/ied-editor.test.snap.js
  test/unit/editors/substation/ied-editor.test.ts
  test/unit/wizards/__snapshots__/ied.test.snap.js
  test/unit/wizards/foundation/references.test.ts
  test/unit/wizards/ied.test.ts
  test/unit/wizards/test-support.ts
Labels: Kind: Enhancement

#730 feat(editors/substation): add read-only l-node-editor
  src/action-icon.ts
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/eq-function-editor.ts
  src/editors/substation/eq-sub-function-editor.ts
  src/editors/substation/foundation.ts
  src/editors/substation/function-editor.ts
  src/editors/substation/l-node-editor.ts
  src/editors/substation/powertransformer-editor.ts
  src/editors/substation/sub-function-editor.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/icons/lnode.ts
  test/testfiles/zeroline/functions.scd
  test/unit/editors/substation/__snapshots__/bay-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/eq-function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/eq-sub-function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/l-node-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/powertransformer-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/sub-function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/substation-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/voltage-level-editor.test.snap.js
  test/unit/editors/substation/bay-editor.test.ts
  test/unit/editors/substation/conducting-equipment-editor.test.ts
  test/unit/editors/substation/eq-function-editor.test.ts
  test/unit/editors/substation/eq-sub-function-editor.test.ts
  test/unit/editors/substation/function-editor.test.ts
  test/unit/editors/substation/l-node-editor.test.ts
  test/unit/editors/substation/powertransformer-editor.test.ts
  test/unit/editors/substation/sub-function-editor.test.ts
  test/unit/editors/substation/voltage-level-editor.test.ts
Labels: Kind: Enhancement

#756 feat(104/values): Added List of IEDs and 104-related DAI to values screen.
  public/js/plugins.js
  src/editors/Communication104.ts
  src/editors/Protocol104.ts
  src/editors/communication104/foundation/foundation.ts
  src/editors/communication104/values-container.ts
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/ied-container.ts
  src/editors/protocol104/network-container.ts
  src/editors/protocol104/values-container.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/integration/editors/Protocol104.test.ts
  test/integration/editors/__snapshots__/Communication104.test.snap.js
  test/integration/editors/__snapshots__/Protocol104.test.snap.js
  test/testfiles/104-protocol.scd
  test/unit/editors/protocol104/__snapshots__/ied-container.test.snap.js
  test/unit/editors/protocol104/__snapshots__/values-container.test.snap.js
  test/unit/editors/protocol104/foundation/foundation.test.ts
  test/unit/editors/protocol104/ied-container.test.ts
  test/unit/editors/protocol104/values-container.test.ts
Labels: Kind: Enhancement

#737 feat(wizards/eqfunction): add create wizard
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/powertransformer-editor.ts
  src/wizards/eqfunction.ts
  src/wizards/wizard-library.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/powertransformer-editor-wizarding-editing.test.ts
  test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/powertransformer-editor.test.snap.js
  test/unit/wizards/__snapshots__/eqfunction.test.snap.js
  test/unit/wizards/eqfunction.test.ts
Labels: Kind: Enhancement

#731 feat(wizards/function): add create wizards for Function, SubFunction, EqFunction and EqSubFunction element
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/eq-function-editor.ts
  src/editors/substation/eq-sub-function-editor.ts
  src/editors/substation/function-editor.ts
  src/editors/substation/powertransformer-editor.ts
  src/editors/substation/sub-function-editor.ts
  src/wizards/eqfunction.ts
  src/wizards/eqsubfunction.ts
  src/wizards/function.ts
  src/wizards/subfunction.ts
  src/wizards/wizard-library.ts
  test/integration/editors/substation/bay-editor-wizarding-editing.test.ts
  test/integration/editors/substation/conducting-equipment-editor-wizarding-editing.test.ts
  test/integration/editors/substation/eq-function-wizarding-editing.test.ts
  test/integration/editors/substation/eq-sub-function-editor-wizarding-editing.test.ts
  test/integration/editors/substation/function-editor.test.ts
  test/integration/editors/substation/powertransformer-editor-wizarding-editing.test.ts
  test/integration/editors/substation/sub-function-editor.test.ts
  test/integration/editors/substation/substation-editor-wizarding-editing.test.ts
  test/integration/editors/substation/voltage-level-editor-wizarding-editing.test.ts
  test/unit/editors/substation/__snapshots__/bay-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/conducting-equipment-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/eq-function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/eq-sub-function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/powertransformer-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/sub-function-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/substation-editor.test.snap.js
  test/unit/editors/substation/__snapshots__/voltage-level-editor.test.snap.js
  test/unit/wizards/__snapshots__/eqfunction.test.snap.js
  test/unit/wizards/__snapshots__/eqsubfunction.test.snap.js
  test/unit/wizards/__snapshots__/function.test.snap.js
  test/unit/wizards/__snapshots__/subfunction.test.snap.js
  test/unit/wizards/eqfunction.test.ts
  test/unit/wizards/eqsubfunction.test.ts
  test/unit/wizards/function.test.ts
  test/unit/wizards/subfunction.test.ts
Labels: Kind: Enhancement

#779 feat(104Protocol): Refactor list of 104 Address and add wizard to edit existing Address Element
  src/editors/protocol104/doi-container.ts
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/ied-container.ts
  src/editors/protocol104/values-container.ts
  src/editors/protocol104/wizards/address.ts
  src/editors/protocol104/wizards/doi.ts
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  test/testfiles/104/valid-addresses-case1.scd
  test/testfiles/104/valid-no-ied.scd
  test/unit/editors/protocol104/__snapshots__/doi-container.test.snap.js
  test/unit/editors/protocol104/__snapshots__/ied-container.test.snap.js
  test/unit/editors/protocol104/__snapshots__/values-container.test.snap.js
  test/unit/editors/protocol104/doi-container.test.ts
  test/unit/editors/protocol104/foundation/foundation.test.ts
  test/unit/editors/protocol104/ied-container.test.ts
  test/unit/editors/protocol104/values-container.test.ts
  test/unit/editors/protocol104/wizards/__snapshots__/address.test.snap.js
  test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js
  test/unit/editors/protocol104/wizards/address.test.ts
  test/unit/editors/protocol104/wizards/doi.test.ts
  test/unit/wizards/test-support.ts
Labels: Kind: Enhancement

#787 refactor(plugging,hosting): make plugin content loading synchronous
  package-lock.json
  package.json
  src/Hosting.ts
  src/Plugging.ts
  src/Setting.ts
  src/foundation/nsdoc.ts
  test/integration/__snapshots__/open-scd.test.snap.js
Labels: Kind: Bug, Reviewed: Prioritized, Priority: Important
