Repository openscd/open-scd, pull requests merged in 2022-08, with the labels that each got.

#927 feat(editor/laterbinding): Added first part for SMV Later Binding Editor
  package-lock.json
  public/js/plugins.js
  src/editors/SMVSubscriberLaterBinding.ts
  src/editors/subscription/smv-laterbinding/svc-laterbinding-list.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/testfiles/editors/LaterBindingSMV.scd
  test/unit/editors/SMVSubscriberLaterBinding.test.ts
  test/unit/editors/__snapshots__/SMVSubscriberLaterBinding.test.snap.js
  test/unit/editors/subscription/smv-laterbinding/__snapshots__/svc-laterbinding-list.test.snap.js
  test/unit/editors/subscription/smv-laterbinding/svc-laterbinding-list.test.ts
Labels: Kind: Enhancement

#922 feat(menu/history): move history to menu plugin
  public/js/plugins.js
  src/Logging.ts
  src/foundation.ts
  src/icons/icons.ts
  src/menu/SclHistory.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/Setting.test.ts
  test/integration/__snapshots__/Setting.test.snap.js
  test/integration/__snapshots__/open-scd.test.snap.js
  test/testfiles/no-history.scd
  test/unit/Logging.test.ts
  test/unit/menu/SclHistory.test.ts
  test/unit/menu/__snapshots__/SclHistory.test.snap.js
Labels: Kind: Enhancement, Kind: Maintenance

#944 feat(editor/laterbinding): Subscribe and unsubscribe from ExtRef for Later Binding (SMV)
  public/js/plugins.js
  src/editors/subscription/foundation.ts
  src/editors/subscription/smv-laterbinding/ext-ref-laterbinding-list.ts
  src/foundation.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/integration/editors/GooseControlSubscription.test.ts
  test/integration/editors/SMVSubscriberLaterBinding.test.ts
  test/integration/editors/SampledValuesSubscription.test.ts
  test/integration/editors/__snapshots__/GooseControlSubscription.test.snap.js
  test/integration/editors/__snapshots__/SampledValuesSubscription.test.snap.js
  test/testfiles/editors/LaterBindingSMV2003.scd
  test/testfiles/editors/LaterBindingSMV2007B4.scd
  test/unit/Plugging.test.ts
  test/unit/editors/SMVSubscriberLaterBinding.test.ts
  test/unit/editors/subscription/foundation.test.ts
  test/unit/editors/subscription/smv-laterbinding/__snapshots__/ext-ref-laterbinding-list.test.snap.js
  test/unit/editors/subscription/smv-laterbinding/ext-ref-laterbinding-list.test.ts
  test/unit/editors/subscription/smv-laterbinding/svc-laterbinding-list.test.ts
  test/unit/foundation.test.ts
Labels: Kind: Enhancement

#926 feat(menu/compareied): ignore attributes/elements when comparing IED Elements
  src/foundation/compare.ts
  src/menu/CompareIED.ts
  src/translations/de.ts
  src/translations/en.ts
  test/testfiles/menu/compare-ied-changed.scd
  test/testfiles/menu/compare-ied-original.scd
  test/unit/foundation/__snapshots__/compare.test.snap.js
  test/unit/foundation/compare.test.ts
  test/unit/menu/CompareIED.test.ts
  test/unit/menu/__snapshots__/CompareIED.test.snap.js
Labels: Kind: Enhancement

#954 chore(ISSUE_TEMPLATE/feature): add optional test file request
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Kind: Documentation

#957 fix(wizard/gsecontrol): Fix schema validation error after creating GSE Control (MinTime)
  src/wizards/gsecontrol.ts
  test/unit/wizards/gsecontrol.test.ts
Labels: Kind: Bug
