Repository openscd/open-scd, pull requests merged in 2022-11, with the labels that each got.

#901 fix(validate-schema): cache validator workers
  src/validators/ValidateSchema.ts
  test/integration/validators/ValidateSchema.test.ts
  test/integration/validators/__snapshots__/ValidateSchema.test.snap.js
Labels: Kind: Bug, Reviewed: Help wanted, Reviewed: Prioritized, Priority: Important

#1067 doc: update roadmap with current feature ideas
  ROADMAP.md
Labels: Kind: Documentation, Reviewed: Help wanted, Kind: Question, Reviewed: Prioritized

#1010 feat(editors/subscription): add subscription supervision support
  src/editors/subscription/foundation.ts
  src/editors/subscription/goose/subscriber-list.ts
  src/editors/subscription/later-binding/ext-ref-later-binding-list.ts
  src/editors/subscription/later-binding/ext-ref-ln-binding-list.ts
  src/editors/subscription/sampledvalues/subscriber-list.ts
  src/foundation.ts
  src/foundation/dai.ts
  test/testfiles/editors/VS893-LaterBindingSMV-LSVS.scd
  test/testfiles/editors/VS893_LaterBindingGOOSE-LGOS.scd
  test/unit/editors/subscription/supervision.test.ts
  test/unit/foundation.test.ts
  test/unit/foundation/dai.test.ts
Labels: Kind: Enhancement
