Repository openscd/open-scd, pull requests merged in 2022-03, with the labels that each got.

#573 fix(wizard/foundation/limits): abstractDataAttributeName
  src/wizards/foundation/limits.ts
  test/integration/wizards/__snapshots__/bda-wizarding-editing.test.snap.js
  test/integration/wizards/__snapshots__/da-wizarding-editing.test.snap.js
  test/unit/wizards/__snapshots__/abstractda.test.snap.js
Labels: Kind: Bug, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#571 feat(plugins/IED): Added Functional Constraint value to DA Container.
  src/editors/ied/da-container.ts
  src/editors/ied/ln-container.ts
  test/unit/editors/ied/__snapshots__/da-container.test.snap.js
  test/unit/editors/ied/da-container.test.ts
Labels: Kind: Enhancement

#551 refactor(foundation): rename Update to Replace
  src/Editing.ts
  src/editors/templates/foundation.ts
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/address.ts
  src/wizards/connectedap.ts
  src/wizards/dataset.ts
  test/integration/Editing.test.ts
  test/unit/Editing.test.ts
  test/unit/editors/subscriberinfo.test.ts
  test/unit/foundation.test.ts
  test/unit/menu/UpdateDescriptionSEL.test.ts
  test/unit/menu/UpdateDescritionABB.test.ts
  test/unit/wizards/abstractda.test.ts
  test/unit/wizards/address.test.ts
  test/unit/wizards/bda.test.ts
  test/unit/wizards/connectedap.test.ts
  test/unit/wizards/da.test.ts
  test/unit/wizards/dataset.test.ts
  test/unit/wizards/foundation.ts
  test/unit/wizards/foundation/references.test.ts
  test/unit/wizards/gse.test.ts
  test/unit/wizards/gsecontrol.test.ts
  test/unit/wizards/ied.test.ts
  test/unit/wizards/optfields.test.ts
  test/unit/wizards/reportcontrol.test.ts
  test/unit/wizards/sampledvaluecontrol.test.ts
  test/unit/wizards/smv.test.ts
  test/unit/wizards/smvopts.test.ts
  test/unit/wizards/subnetwork.test.ts
  test/unit/wizards/trgops.test.ts
  test/unit/zeroline/BayEditor.test.ts
  test/unit/zeroline/SubstationEditor.test.ts
  test/unit/zeroline/VoltageLevelEditor.test.ts
Labels: Kind: Maintenance

#544 feat(wizards/reportcontrol): add create wizard
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/fcda.ts
  src/wizards/foundation/finder.ts
  src/wizards/foundation/functions.ts
  src/wizards/optfields.ts
  src/wizards/reportcontrol.ts
  src/wizards/trgops.ts
  test/integration/wizards/reportcontrol-wizarding-editing.test.ts
  test/testfiles/wizards/reportcontrol.scd
  test/unit/foundation.test.ts
  test/unit/wizards/__snapshots__/connectedap-pattern.test.snap.js
  test/unit/wizards/__snapshots__/optfields.test.snap.js
  test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
  test/unit/wizards/__snapshots__/smv.test.snap.js
  test/unit/wizards/__snapshots__/subnetwork.test.snap.js
  test/unit/wizards/__snapshots__/trgops.test.snap.js
  test/unit/wizards/foundation/finder.test.ts
  test/unit/wizards/foundation/functions.test.ts
  test/unit/wizards/reportcontrol.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized

#585 feat(Editing): check globally for ID uniqueness
  src/Editing.ts
  src/translations/de.ts
  src/translations/en.ts
  test/testfiles/Editing.scd
  test/unit/Editing.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized

#570 feat(plugins/IED): Add icon set to IED editor containers
  src/Logging.ts
  src/editors/ied/access-point-container.ts
  src/editors/ied/ied-container.ts
  src/editors/ied/ldevice-container.ts
  src/editors/ied/server-container.ts
  src/editors/singlelinediagram/sld-drawing.ts
  src/icons/icons.ts
  src/icons/ied-icons.ts
  src/menu/Help.ts
  src/wizards/clientln.ts
  src/wizards/commmap-wizards.ts
  src/wizards/controlwithiedname.ts
  src/zeroline-pane.ts
  src/zeroline/foundation.ts
  src/zeroline/ied-editor.ts
  test/unit/editors/ied/__snapshots__/access-point-container.test.snap.js
  test/unit/editors/ied/__snapshots__/da-container.test.snap.js
  test/unit/editors/ied/__snapshots__/do-container.test.snap.js
  test/unit/editors/ied/__snapshots__/ied-container.test.snap.js
  test/unit/editors/ied/__snapshots__/ldevice-container.test.snap.js
  test/unit/editors/ied/__snapshots__/ln-container.test.snap.js
  test/unit/editors/ied/__snapshots__/server-container.test.snap.js
Labels: Kind: Enhancement

#581 style(wizard-checkbox): highlight human readable information
  src/wizard-checkbox.ts
Labels: Reviewed: Prioritized

#582 fix(editors/template): properly update xxxType list after ad/editing
  src/editors/Templates.ts
Labels: Kind: Bug, Reviewed: Prioritized

#594 fix(action-pane): adjust css rules for icon slot
  src/action-pane.ts
Labels: Kind: Bug

#601 feat(editors/Substation): Add PowerTransformer Components to Substation Editor
  src/editors/singlelinediagram/wizards/powertransformer.ts
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/powertransformer.ts
  src/wizards/wizard-library.ts
  src/zeroline/bay-editor.ts
  src/zeroline/conducting-equipment-editor.ts
  src/zeroline/foundation.ts
  src/zeroline/powertransformer-editor.ts
  src/zeroline/substation-editor.ts
  src/zeroline/voltage-level-editor.ts
  test/unit/editors/ied/__snapshots__/da-container.test.snap.js
  test/unit/editors/ied/__snapshots__/do-container.test.snap.js
  test/unit/editors/singlelinediagram/wizards/__snapshots__/powertransformer.test.snap.js
  test/unit/editors/singlelinediagram/wizards/bay.test.ts
  test/unit/editors/singlelinediagram/wizards/conductingequipment.test.ts
  test/unit/editors/singlelinediagram/wizards/powertransformer.test.ts
  test/unit/wizards/__snapshots__/powertransformer.test.snap.js
  test/unit/wizards/foundation.ts
  test/unit/wizards/powertransformer.test.ts
  test/unit/zeroline/VoltageLevelEditor.test.ts
  test/unit/zeroline/__snapshots__/bay-editor.test.snap.js
  test/unit/zeroline/__snapshots__/powertransformer-editor.test.snap.js
  test/unit/zeroline/__snapshots__/substation-editor.test.snap.js
  test/unit/zeroline/__snapshots__/voltage-level-editor.test.snap.js
  test/unit/zeroline/powertransformer-editor.test.ts
Labels: Kind: Enhancement

#599 refactor(wizards/reportcontrol): use report update action
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/gsecontrol.ts
  src/wizards/reportcontrol.ts
  src/wizards/sampledvaluecontrol.ts
  test/unit/wizards/gsecontrol.test.ts
  test/unit/wizards/reportcontrol.test.ts
  test/unit/wizards/sampledvaluecontrol.test.ts
Labels: Kind: Bug

#603 feat(editors/template/lnodetype-wizards): make use of -7-420 NSD
  public/xml/IEC_61850-7-420_2019A4.nsd
  src/editors/Templates.ts
  src/editors/templates/lnodetype-wizard.ts
  test/integration/editors/templates/__snapshots__/lnodetype-wizard.test.snap.js
  test/integration/editors/templates/lnodetype-wizard.test.ts
Labels: Kind: Enhancement

#645 fix(wizards/subnetwork): incorrect title for create wizard
  src/wizards/subnetwork.ts
  test/unit/wizards/__snapshots__/subnetwork.test.snap.js
Labels: Kind: Bug
