Repository openscd/open-scd, pull requests merged in 2022-07, with the labels that each got.

#844 feat(editors/publisher): filter for control blocks and DataSets
  public/js/plugins.js
  src/editors/Publisher.ts
  src/editors/publisher/data-set-editor.ts
  src/editors/publisher/gse-control-editor.ts
  src/editors/publisher/report-control-editor.ts
  src/editors/publisher/sampled-value-control-editor.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/unit/editors/Publisher.test.ts
  test/unit/editors/__snapshots__/Publisher.test.snap.js
  test/unit/editors/publisher/__snapshots__/data-set-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/gse-control-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/report-control-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/sampled-value-control-editor.test.snap.js
  test/unit/editors/publisher/data-set-editor.test.ts
  test/unit/editors/publisher/gse-control-editor.test.ts
  test/unit/editors/publisher/report-control-editor.test.ts
  test/unit/editors/publisher/sampled-value-control-editor.test.ts
Labels: Kind: Enhancement

#843 fix(Pluggin/Hosting): allocate menu plugin content next to its list item
  src/Hosting.ts
  src/Plugging.ts
  src/open-scd.ts
  test/integration/__snapshots__/open-scd.test.snap.js
Labels: Kind: Bug

#806 feat(menu/VirtualTemplateIED): automatically create virtual IEDs
  public/js/plugins.js
  src/foundation.ts
  src/menu/VirtualTemplateIED.ts
  src/menu/virtualtemplateied/foundation.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/testfiles/virtualied/specificfromfunctions.ssd
  test/unit/menu/VirtualTemplateIED.test.ts
  test/unit/menu/__snapshots__/VirtualTemplateIED.test.snap.js
  test/unit/menu/virtualtemplateied/__snapshots__/foundation.test.snap.js
  test/unit/menu/virtualtemplateied/foundation.test.ts
Labels: Kind: Enhancement

#852 fix(editors/substation): update on action
  src/editors/substation/bay-editor.ts
  src/editors/substation/conducting-equipment-editor.ts
  src/editors/substation/eq-function-editor.ts
  src/editors/substation/eq-sub-function-editor.ts
  src/editors/substation/function-editor.ts
  src/editors/substation/ied-editor.ts
  src/editors/substation/l-node-editor.ts
  src/editors/substation/powertransformer-editor.ts
  src/editors/substation/sub-function-editor.ts
  src/editors/substation/substation-editor.ts
  src/editors/substation/voltage-level-editor.ts
  src/editors/substation/zeroline-pane.ts
Labels: Kind: Bug, Kind: Breaking

#879 fix(editing): failing auto-validation after editor actions
  src/Editing.ts
Labels: Kind: Bug, Priority: Urgent

#874 fix(editor/104): Small improvements and fix.
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/wizards/selectDo.ts
Labels: Kind: Bug

#881 fix(editor/SingleLineDiagram): Fixed redrawing when new document loaded
  src/editors/SingleLineDiagram.ts
Labels: Kind: Bug

#888 fix(mergeWizard): insert element at valid position
  src/wizards.ts
Labels: Kind: Bug, Reviewed: Help wanted, Reviewed: Prioritized, Priority: Important

#889 fix(editing): don't validate after no-op action
  src/Editing.ts
  test/unit/Editing.test.ts
Labels: Kind: Bug, Reviewed: Help wanted, Reviewed: Prioritized

#903 feat(menu/compareied): Add new menu option to compare a IED with one from template project
  public/js/plugins.js
  src/foundation/compare.ts
  src/menu/CompareIED.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/testfiles/foundation/compare-changed.cid
  test/testfiles/foundation/compare-original.cid
  test/testfiles/menu/compare-ied-changed.scd
  test/testfiles/menu/compare-ied-original.scd
  test/unit/foundation/__snapshots__/compare.test.snap.js
  test/unit/foundation/compare.test.ts
  test/unit/menu/CompareIED.test.ts
  test/unit/menu/SubscriberInfo.test.ts
  test/unit/menu/__snapshots__/CompareIED.test.snap.js
Labels: Kind: Enhancement

#911 feat(editors/publisher): add read only data set element editor
  src/editors/Publisher.ts
  src/editors/publisher/data-set-editor.ts
  src/editors/publisher/data-set-element-editor.ts
  src/editors/publisher/foundation.ts
  src/editors/publisher/gse-control-editor.ts
  src/editors/publisher/report-control-editor.ts
  src/editors/publisher/sampled-value-control-editor.ts
  src/translations/de.ts
  src/translations/en.ts
  test/unit/editors/publisher/__snapshots__/data-set-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/data-set-element-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/gse-control-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/report-control-editor.test.snap.js
  test/unit/editors/publisher/__snapshots__/sampled-value-control-editor.test.snap.js
  test/unit/editors/publisher/data-set-editor.test.ts
  test/unit/editors/publisher/data-set-element-editor.test.ts
  test/unit/editors/publisher/gse-control-editor.test.ts
  test/unit/editors/publisher/report-control-editor.test.ts
  test/unit/editors/publisher/sampled-value-control-editor.test.ts
Labels: Kind: Enhancement
