Repository openscd/open-scd, pull requests merged in 2022-02, with the labels that each got.

#527 style: make landing buttons reactive
  src/open-scd.ts
Labels: Kind: Bug, Reviewed: Prioritized

#528 style(action-pane): clip heading label
  src/action-pane.ts
Labels: Kind: Bug

#529 style: center landing icons
  src/open-scd.ts
Labels: Kind: Bug, Reviewed: Prioritized

#531 fix(menu/Help): incorrect import of markup parser
  src/menu/Help.ts
Labels: Kind: Breaking, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#519 feat(wizards/smv): add edit wizard and allow access from sampledvaluecontrol wizard
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/address.ts
  src/wizards/sampledvaluecontrol.ts
  src/wizards/smv.ts
  test/foundation.ts
  test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
  test/unit/wizards/__snapshots__/address.test.snap.js
  test/unit/wizards/__snapshots__/gse.test.snap.js
  test/unit/wizards/__snapshots__/smv.test.snap.js
  test/unit/wizards/smv.test.ts
Labels: Reviewed: Duplicate, Kind: Enhancement

#538 refactor(Plugins): improve extentions UI
  src/Plugging.ts
  test/integration/__snapshots__/open-scd.test.snap.js
Labels: Kind: Maintenance

#537 feat(wizard-checkbox): web component for xs:boolean XML attributes
  src/editors/templates/foundation.ts
  src/editors/templates/lnodetype-wizard.ts
  src/foundation.ts
  src/wizard-checkbox.ts
  src/wizards/abstractda.ts
  src/wizards/da.ts
  src/wizards/gsecontrol.ts
  src/wizards/optfields.ts
  src/wizards/reportcontrol.ts
  src/wizards/sampledvaluecontrol.ts
  src/wizards/trgops.ts
  test/integration/editors/templates/__snapshots__/lnodetype-wizard.test.snap.js
  test/integration/editors/templates/lnodetype-wizard.test.ts
  test/integration/wizards/__snapshots__/bda-wizarding-editing.test.snap.js
  test/integration/wizards/__snapshots__/da-wizarding-editing.test.snap.js
  test/integration/wizards/bda-wizarding-editing.test.ts
  test/integration/wizards/da-wizarding-editing.test.ts
  test/integration/wizards/reportcontrol-wizarding-editing.test.ts
  test/unit/wizard-checkbox.test.ts
  test/unit/wizards/__snapshots__/abstractda.test.snap.js
  test/unit/wizards/__snapshots__/gsecontrol.test.snap.js
  test/unit/wizards/__snapshots__/optfields.test.snap.js
  test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
  test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js
  test/unit/wizards/__snapshots__/trgops.test.snap.js
  test/unit/wizards/bda.test.ts
  test/unit/wizards/da.test.ts
  test/unit/wizards/gsecontrol.test.ts
  test/unit/wizards/optfields.test.ts
  test/unit/wizards/reportcontrol.test.ts
  test/unit/wizards/trgops.test.ts
Labels: Kind: Enhancement

#536 feat(wizard/sampledvaluecontrol): allow removing incl. referenced elements
  src/wizards/sampledvaluecontrol.ts
  test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
  test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js
  test/unit/wizards/sampledvaluecontrol.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized

#547 feat(wizards/smvopts): add edit wizard
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/sampledvaluecontrol.ts
  src/wizards/smvopts.ts
  test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
  test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js
  test/unit/wizards/__snapshots__/smvopts.test.snap.js
  test/unit/wizards/smvopts.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized
