Repository openscd/open-scd, pull requests merged in 2022-01, with the labels that each got.

#470 fix(editors/SingleLineDiagram): Switching substation will recalculated viewbox and reset panzoom
  src/editors/SingleLineDiagram.ts
Labels: Kind: Bug

#469 fix(editors/template/lnodetype): fix incorrect pattern for lnClass
  src/foundation.ts
  test/foundation.ts
  test/integration/editors/templates/__snapshots__/lnodetype-wizard.test.snap.js
  test/integration/editors/templates/lnodetype-wizard.test.ts
  test/unit/editors/templates/lnodetype-wizard.test.ts
Labels: Kind: Bug, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#448 refactor(editors/connectedap-editor): move wizards to wizard library
  src/editors/communication/connectedap-editor.ts
  src/editors/communication/p-types.ts
  src/editors/communication/subnetwork-editor.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/connectedap.ts
  src/wizards/foundation/p-types.ts
  test/foundation.ts
  test/integration/editors/communication/__snapshots__/connectedap-editor-wizarding.test.snap.js
  test/integration/editors/communication/__snapshots__/subnetwork-editor-wizarding.test.snap.js
  test/integration/editors/communication/connectedap-editor-wizarding-editing.test.ts
  test/integration/editors/communication/connectedap-editor-wizarding.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding.test.ts
  test/unit/editors/communication/ConnectedAPEditor.test.ts
  test/unit/wizards/__snapshots__/connectedap-pattern.test.snap.js
  test/unit/wizards/__snapshots__/connectedap.test.snap.js
  test/unit/wizards/connectedap-pattern.test.ts
  test/unit/wizards/connectedap.test.ts
Labels: Kind: Maintenance, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#424 feat(UpdateDescriptionSEL): add menu type plugin for SEL specific IEDs
  public/js/plugins.js
  src/menu/UpdateDescriptionSEL.ts
  src/translations/de.ts
  src/translations/en.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/testfiles/updatedesc/testSignalListComma.csv
  test/testfiles/updatedesc/testSignalListSemicolon.csv
  test/testfiles/updatedesc/updatedescSEL.scd
  test/unit/menu/UpdateDescriptionSEL.test.ts
  test/unit/menu/__snapshots__/UpdateDescriptionSEL.test.snap.js
Labels: Kind: Enhancement, Reviewed: Prioritized

#477 feat(zeroline): show SampledValueControl for IED and whole project
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/sampledvaluecontrol.ts
  src/zeroline-pane.ts
  src/zeroline/ied-editor.ts
  test/integration/zeroline-pane.test.ts
  test/testfiles/wizards/sampledvaluecontrol.scd
  test/unit/__snapshots__/zeroline-pane.test.snap.js
  test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js
  test/unit/wizards/sampledvaluecontrol.test.ts
  test/unit/zeroline/__snapshots__/ied-editor.test.snap.js
  test/unit/zeroline/ied-editor.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#481 feat(editors/ied): Changed icon of IED Editor
  public/js/plugins.js
  test/integration/__snapshots__/open-scd.test.snap.js
Labels: Kind: Enhancement

#482 fix(zeroline): SampledValueControl Test for IED
  test/unit/wizards/sampledvaluecontrol.test.ts
  test/unit/zeroline/ied-editor.test.ts
Labels: Kind: Bug

#492 feat(wizards/reportcontrol): access edit wizard from select wizard
  src/foundation.ts
  src/wizards/reportcontrol.ts
  src/zeroline-pane.ts
  src/zeroline/ied-editor.ts
  test/integration/wizards/reportcontrol-wizarding-editing.test.ts
  test/testfiles/wizards/reportcontrol.scd
  test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
Labels: Kind: Enhancement, Reviewed: Prioritized

#493 feat(wizards/reportcontrol): add remove option to edit wizard
  src/wizards/reportcontrol.ts
  test/integration/wizards/reportcontrol-wizarding-editing.test.ts
  test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
  test/unit/wizards/reportcontrol.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized

#495 fix(editors/SingleLineDiagram): added check if a substation is available/selected before drawing
  src/editors/SingleLineDiagram.ts
Labels: Kind: Bug

#494 feat(wizards/reportcontrol): added new IED wizard to update name/description
  src/editors/ied/ied-container.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/foundation/references.ts
  src/wizards/ied.ts
  src/wizards/wizard-library.ts
  src/zeroline/ied-editor.ts
  test/testfiles/wizards/ied.scd
  test/unit/editors/ied/__snapshots__/ied-container.test.snap.js
  test/unit/wizards/__snapshots__/ied.test.snap.js
  test/unit/wizards/foundation.ts
  test/unit/wizards/foundation/references.test.ts
  test/unit/wizards/ied.test.ts
  test/unit/zeroline/__snapshots__/ied-editor.test.snap.js
Labels: Kind: Enhancement

#501 fix(editors): In IED and SLD Editors fixed preserving the selection (IED or Substation)
  src/editors/IED.ts
  src/editors/SingleLineDiagram.ts
  test/integration/editors/IED.test.ts
  test/integration/editors/__snapshots__/IED.test.snap.js
Labels: Kind: Bug, Priority: Important

#505 feat(wizards/reportcontrol): allow basic ReportControl manipulation capability
  src/foundation.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/dataset.ts
  src/wizards/fcda.ts
  src/wizards/optfields.ts
  src/wizards/reportcontrol.ts
  src/wizards/reportcontrolblock.ts
  src/wizards/trgops.ts
  src/wizards/wizard-library.ts
  src/zeroline-pane.ts
  src/zeroline/ied-editor.ts
  test/foundation.ts
  test/integration/wizards/reportcontrol-wizarding-editing.test.ts
  test/integration/zeroline-pane.test.ts
  test/integration/zeroline/ied-editor-wizarding-integration.test.ts
  test/testfiles/wizards/reportcontrol.scd
  test/unit/__snapshots__/zeroline-pane.test.snap.js
  test/unit/wizards/__snapshots__/dataset.test.snap.js
  test/unit/wizards/__snapshots__/optfields.test.snap.js
  test/unit/wizards/__snapshots__/reportcontrol.test.snap.js
  test/unit/wizards/__snapshots__/trgops.test.snap.js
  test/unit/wizards/dataset.test.ts
  test/unit/wizards/fcda.test.ts
  test/unit/wizards/optfields.test.ts
  test/unit/wizards/reportcontrol.test.ts
  test/unit/wizards/trgops.test.ts
  test/unit/zeroline/__snapshots__/ied-editor.test.snap.js
  test/unit/zeroline/ied-editor.test.ts
Labels: Kind: Enhancement

#512 fix(wizards/fcda): make sure lnInst is non empty string
  src/wizards/fcda.ts
  test/integration/wizards/fcda-wizarding-editing-integration.test.ts
  test/unit/wizards/fcda.test.ts
Labels: Kind: Bug, Reviewed: Prioritized, Priority: Urgent, Priority: Important

#507 refactor(wizards/gsecontrol): use dynamic sub-wizards
  src/wizards/dataset.ts
  src/wizards/gse.ts
  src/wizards/gsecontrol.ts
  src/zeroline-pane.ts
  src/zeroline/ied-editor.ts
  test/integration/wizards/gsecontrolwizarding-editing.test.ts
  test/testfiles/wizards/gsecontrol.scd
  test/unit/wizards/__snapshots__/dataset.test.snap.js
  test/unit/wizards/__snapshots__/gse.test.snap.js
Labels: Kind: Enhancement, Reviewed: Prioritized

#510 feat(wizards/sampledvaluecontrol): add edit wizards accessable from selection
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/foundation/enums.ts
  src/wizards/gsecontrol.ts
  src/wizards/sampledvaluecontrol.ts
  src/zeroline-pane.ts
  src/zeroline/ied-editor.ts
  test/integration/wizards/sampledvaluecontrol-wizarding-editing.test.ts
  test/testfiles/wizards/sampledvaluecontrol.scd
  test/unit/wizards/__snapshots__/gsecontrol.test.snap.js
  test/unit/wizards/__snapshots__/sampledvaluecontrol.test.snap.js
  test/unit/wizards/sampledvaluecontrol.test.ts
Labels: Kind: Enhancement, Reviewed: Prioritized
