Repository openscd/open-scd, pull requests merged in 2022-06, with the labels that each got.

#799 feat(104/AddAddress): Add Address Element (including SCL Private Element) for first set of CDC's
  src/editors/protocol104/doi-container.ts
  src/editors/protocol104/foundation/cdc.ts
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/foundation/private.ts
  src/editors/protocol104/values-container.ts
  src/editors/protocol104/wizards/address.ts
  src/editors/protocol104/wizards/doi.ts
  src/editors/protocol104/wizards/selectDoi.ts
  src/editors/protocol104/wizards/selectTi.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/foundation/finder.ts
  test/unit/editors/protocol104/__snapshots__/values-container.test.snap.js
  test/unit/editors/protocol104/doi-container.test.ts
  test/unit/editors/protocol104/foundation/foundation.test.ts
  test/unit/editors/protocol104/wizards/__snapshots__/address.test.snap.js
  test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js
  test/unit/editors/protocol104/wizards/address.test.ts
  test/unit/editors/protocol104/wizards/doi.test.ts
Labels: Kind: Enhancement

#800 feat(general): prevent losing data on user navigation
  index.html
Labels: Kind: Enhancement

#803 feat(104/Address): Added "Control" handling of CDC and first part of refactoring after discussion.
  src/editors/protocol104/foundation/cdc.ts
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/foundation/private.ts
  src/editors/protocol104/wizards/doi.ts
  src/editors/protocol104/wizards/prepareAddress.ts
  src/editors/protocol104/wizards/selectDoi.ts
  src/editors/protocol104/wizards/selectTi.ts
  src/translations/de.ts
  src/translations/en.ts
  test/testfiles/104/valid-addresses.scd
  test/testfiles/104/valid-empty-addresses.scd
  test/unit/editors/protocol104/doi-container.test.ts
  test/unit/editors/protocol104/foundation/foundation.test.ts
  test/unit/editors/protocol104/foundation/selectDoi.test.ts
  test/unit/editors/protocol104/ied-container.test.ts
  test/unit/editors/protocol104/values-container.test.ts
  test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js
  test/unit/editors/protocol104/wizards/address.test.ts
  test/unit/editors/protocol104/wizards/doi.test.ts
Labels: Kind: Enhancement

#804 feat(104/Address): Changed handling when/how Address with inverted attribute are created
  src/editors/protocol104/foundation/cdc.ts
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/wizards/prepareAddress.ts
  src/editors/protocol104/wizards/selectDoi.ts
  src/translations/de.ts
  src/translations/en.ts
Labels: Kind: Enhancement

#816 feat(ied-editor/init-dai): Initialize the DOI/SDI/DAI Structure when not available
  README.md
  package-lock.json
  src/editors/IED.ts
  src/editors/ied/da-container.ts
  src/foundation/dai.ts
  src/translations/de.ts
  src/translations/en.ts
  src/wizards/dai.ts
  test/unit/foundation/dai.test.ts
  test/unit/foundation/scl.test.ts
  test/unit/wizards/test-support.ts
Labels: Kind: Enhancement

#814 fix(editing): reactively update after changes to doc
  public/js/plugins.js
  src/Editing.ts
  src/Hosting.ts
  src/Plugging.ts
  src/validators/ValidateTemplates.ts
  src/validators/templates/foundation.ts
  test/integration/__snapshots__/open-scd.test.snap.js
  test/integration/editors/cleanup/control-blocks-container.test.ts
  test/integration/editors/cleanup/datasets-container.test.ts
  test/integration/editors/subscription/Subscription.test.ts
  test/integration/editors/templates/Templates.test.ts
  test/integration/validators/ValidateSchema.test.ts
  test/integration/validators/ValidateTemplates.test.ts
  test/integration/validators/__snapshots__/ValidateSchema.test.snap.js
  test/integration/validators/__snapshots__/ValidateTemplates.test.snap.js
  test/unit/Editing.test.ts
  test/unit/validators/ValidateTemplates.test.ts
Labels: Kind: Bug, Reviewed: Help wanted, Reviewed: Prioritized, Priority: Urgent, Priority: Important, Ready for development

#821 feat(104/ShowDOIWizard): Show detailed info about known/found TIs
  src/editors/protocol104/wizards/doi.ts
  test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js
  test/unit/editors/protocol104/wizards/doi.test.ts
Labels: Kind: Enhancement

#820 feat(104/ExpectedValue): Handling Enum Values as Expected Values in 104 address elements.
  src/editors/protocol104/doi-container.ts
  src/editors/protocol104/foundation/actions.ts
  src/editors/protocol104/foundation/cdc.ts
  src/editors/protocol104/foundation/foundation.ts
  src/editors/protocol104/foundation/private.ts
  src/editors/protocol104/ied-container.ts
  src/editors/protocol104/values-container.ts
  src/editors/protocol104/wizards/address.ts
  src/editors/protocol104/wizards/createAddresses.ts
  src/editors/protocol104/wizards/doi.ts
  src/editors/protocol104/wizards/prepareAddress.ts
  src/editors/protocol104/wizards/selectDoi.ts
  src/translations/de.ts
  src/translations/en.ts
  test/testfiles/104/valid-addresses.scd
  test/testfiles/104/valid-empty-addresses.scd
  test/testfiles/104/valid-no-ied.scd
  test/unit/editors/protocol104/__snapshots__/values-container.test.snap.js
  test/unit/editors/protocol104/doi-container.test.ts
  test/unit/editors/protocol104/foundation/actions.test.ts
  test/unit/editors/protocol104/foundation/cdc.test.ts
  test/unit/editors/protocol104/foundation/foundation.test.ts
  test/unit/editors/protocol104/foundation/private.test.ts
  test/unit/editors/protocol104/ied-container.test.ts
  test/unit/editors/protocol104/network-container.test.ts
  test/unit/editors/protocol104/values-container.test.ts
  test/unit/editors/protocol104/wizards/__snapshots__/address.test.snap.js
  test/unit/editors/protocol104/wizards/__snapshots__/createAddresses.test.snap.js
  test/unit/editors/protocol104/wizards/__snapshots__/doi.test.snap.js
  test/unit/editors/protocol104/wizards/__snapshots__/selectDoi.test.snap.js
  test/unit/editors/protocol104/wizards/address.test.ts
  test/unit/editors/protocol104/wizards/createAddresses.test.ts
  test/unit/editors/protocol104/wizards/doi.test.ts
  test/unit/editors/protocol104/wizards/selectDoi.test.ts
Labels: Kind: Enhancement

#822 feat(wizards/ied): added new textfields for IED properties
  src/wizards/ied.ts
  test/unit/wizards/__snapshots__/ied.test.snap.js
  test/unit/wizards/ied.test.ts
Labels: Kind: Enhancement, Reviewed: Help wanted

#833 fix(104/address): Input fields are reset when using multiple time
  src/editors/protocol104/wizards/address.ts
Labels: Kind: Bug

#819 fix(communication): display changes to ConnectedAPs in SubNetworks
  src/editors/Communication.ts
  src/editors/communication/subnetwork-editor.ts
  src/foundation.ts
  src/wizards/foundation/p-types.ts
  test/integration/editors/communication/__snapshots__/subnetwork-editor-wizarding-editing.test.snap.js
  test/integration/editors/communication/subnetwork-editor-wizarding-editing.test.ts
  test/integration/editors/communication/subnetwork-editor-wizarding.test.ts
  test/unit/editors/communication/__snapshots__/subnetwork-editor.test.snap.js
  test/unit/editors/communication/subnetwork-editor.test.ts
Labels: Kind: Bug, Reviewed: Prioritized, Priority: Urgent, Priority: Important, Ready for development
